name: utopia_recruitment_task
description: Zadanie rekrutacyjne Utopia USS
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  rxdart: ^0.27.3

  freezed_annotation: ^1.0.0
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  url_launcher: ^6.0.18

  flutter_slidable: ^1.2.0

  animations: ^2.0.2
  flutter_svg: ^1.0.0
  font_awesome_flutter: ^9.2.0
  jiffy: ^5.0.0


  flutter_spinkit: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

dev_dependencies:
  build_runner: ^2.1.5
  flutter_native_splash: ^2.0.5
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  freezed: ^1.0.0


flutter_native_splash:
  color: "#f6d7ef"
  image: assets/splash.png
  android: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
